### ISSUE TITLE
[Bug]: The max task num is not same as defined in config and it would be one more than the number defined

### ISSUE THREAD

**Issue by zhuwenxing** [zilliztech/milvus-cdc#11]
### Current Behavior

```
[2023-04-12 13:17:51 - INFO - ci_test]: num_tasks: 101 (test_cdc_create.py:364)
FAILED
testcases/test_cdc_create.py:314 (TestCDCCreate.test_cdc_for_cdc_task_large_than_max_num)
101 != 100
```

### Expected Behavior

the max task number is equal to the defined number 100.

### Steps To Reproduce

set the task.maxNum: 100
create 103 tasks

### Anything else?

Creating a task will be failed if the task number is larger than 101. So I guess the boundary is not set correctly.

**Comment by zhuwenxing** [comment]
see https://github.com/zilliztech/milvus-cdc/actions/runs/4674970445/jobs/8279623700?pr=10
![image](https://user-images.githubusercontent.com/12268675/231370410-4fccb240-7c6b-475b-886b-81838ceed618.png)

**Comment by SimFG** [comment]
From the test result, it seems to be fixed
