### ISSUE TITLE
milvus-cdc 任务创建失败

### ISSUE THREAD

**Issue by 1292253144** [zilliztech/milvus-cdc#124]
### Current Behavior

1、./milvus-cdc server启动后
2、 curl -X POST http://0.0.5.1:8444/cdc -H "Content-Type: application/json" -d '{
  "request_type": "create",
  "request_data": {
    "milvus_connect_param": {
      "host": "10.0.0.0",
      "port": 19530,
      "username": "root",
      "password": "password",
      "enable_tls": false,
      "connect_timeout": 10
    },
    "collection_infos": [
      {
        "name": "*"
      }
    ],
    "rpc_channel_info": {
      "name": "by-dev-replicate-msg"
    }
  }
}'
3、服务中断
![image](https://github.com/user-attachments/assets/da029e08-fc55-497a-84c4-5524cfc75910)

### Expected Behavior

目的是做数据迁移

### Environment

milvus集群 版本2.4.1
CDC版本：v1.0.0

**Comment by SimFG** [comment]
@1292253144 please upload the cdc full log

**Comment by 1292253144** [comment]
服务启动log：
]# ./milvus-cdc server &
[1] 17849
(base) [root@mysqlispdb5 milvus-cdc1.0.0]#
(base) [root@mysqlispdb5 milvus-cdc1.0.0]# {"level":"warn","ts":"2024-09-03T19:13:33.040+0800","logger":"etcd-client","caller":"v3@v3.5.5/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00010efc0/localhost:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp [::1]:2379: connect: connection refused\""}
[2024/09/03 19:13:33.041 +08:00] [INFO] [tag/tag.go:36] ["base info"] [BuildTime=unknown] [GitCommit=unknown] [GoVersion=unknown]
[2024/09/03 19:13:33.079 +08:00] [INFO] [server/server.go:56] ["start server..."]

创建任务log：
![image](https://github.com/user-attachments/assets/2c3f1055-285d-4f60-97d4-4e64703f2e06)

**Comment by SimFG** [comment]
@1292253144 the full log file is in the /tmp/cdc_log dir

**Comment by 1292253144** [comment]
执行了多次创建任务
[cdc.log](https://github.com/user-attachments/files/16848200/cdc.log)

**Comment by 1292253144** [comment]
前面的几次失败原因都找到了，麻烦看最后两次日志，同样的输出
![image](https://github.com/user-attachments/assets/702e4c54-d5a6-439c-8a12-a8f301dceaa6)

**Comment by SimFG** [comment]
In the last two times, it seems that the CDC did not receive the create request. You can try to list all the tasks and then delete them all, and then resend a create request. Because from the log, it seems that no exception occurred in the CDC

**Comment by SimFG** [comment]
i will close the issue. If you meet other problems, please give me a new issue.
