### ISSUE TITLE
[Bug]: Insert synchronization operation always fail after running CDC and related Milvus for a period of time.

### ISSUE THREAD

**Issue by WuYiFan0108** [zilliztech/milvus-cdc#38]
### Current Behavior

When I insert some random data into upstream Milvus, CDC task paused with error `fail to handle the op message pack, err:attempt #0: channel=by-dev-rootcoord-dml_3_446490503812650825v0: channel not found: ... attempt #58: channel=by-dev-rootcoord-dml_3_446490503812650825v0: channel not found: attempt #59: channel=by-dev-rootcoord-dml_3_446490503812650825v0: channel not found"`

### Expected Behavior

Milvus-CDC successfully synchronized insert operation to downstream Milvus.

### Steps To Reproduce

1. Start CDC server and create new CDC task
2. Specify upstream Milvus to run hello_milvus.py from https://raw.githubusercontent.com/milvus-io/pymilvus/master/examples/hello_milvus.py
3. Check downstream Milvus to see if Milvus-CDC works and find that insert operation didn`t synchronized.
4. Check the CDC task status and find that the CDC task is paused due to the above error.

### Environment

Ubuntu 22.04 LTS
Milvus Cluster 2.3.3
Milvus Cluster with Pulsar as MQ
2 * Milvus Cluster deployed on Kubernetes, one as upstream and other one as downstream
Milvus-CDC built from source
Milvus-CDC connects to upstream and downstream Milvus with ClusterIP

### Anything else?

I've tried pausing and resuming CDC task, deleting old CDC task and creating a new CDC task, or restarting the CDC server, nothing helps.

**Comment by SimFG** [comment]
@WuYiFan0108 please check if the dml channel num setting are same in the source and target milvus?

**Comment by WuYiFan0108** [comment]
> @WuYiFan0108 please check if the dml channel num setting are same in the source and target milvus?
Do you mean rootCoord.dmlChannelNum in milvus.yaml? They are same in the source and target milvus.
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/76df2333-ed5c-47a3-acc5-1d6f28b8f111)

**Comment by WuYiFan0108** [comment]
@SimFG By the way, I found that only calls insert() does not trigger this error, server just stuck with message `[writer/channel_writer.go:117] ["replicate msg"] [type=Insert]`. 
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/8aac4154-d254-4071-8487-3f9ae70dc40d)
Calling flush() is the real cause of this error.

**Comment by SimFG** [comment]
@WuYiFan0108 can you show me the `etcd.endpoints/etcd.rootPath` configs in the source and target milvus?

**Comment by WuYiFan0108** [comment]
> @WuYiFan0108 can you show me the `etcd.endpoints/etcd.rootPath` configs in the source and target milvus?

Sure, this is the source milvus's etcd config: 
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/5188d0ae-0fd2-40b1-8a3e-a239fe0b60e3)
This is the target milvus's etcd config: 
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/c0e4c091-2c28-48a1-ab9f-771f8f0f131f)

**Comment by SimFG** [comment]
@WuYiFan0108 How did you deploy two etcd services? 
Judging from the current error message, it should be that target milvus has read the etcd information of source milvus.

**Comment by WuYiFan0108** [comment]
> @WuYiFan0108 How did you deploy two etcd services? Judging from the current error message, it should be that target milvus has read the etcd information of source milvus.

Using Milvus Helm Chart, didn`t make any changes to etcd related config.
Link: https://artifacthub.io/packages/helm/milvus-helm/milvus

**Comment by SimFG** [comment]
@WuYiFan0108 can you use the latest dev image to try it again? because i learn that it maybe cause the milvus issue 
image tag: milvusdb/milvus:2.3-20231227-26b1853c-amd64

**Comment by WuYiFan0108** [comment]
> @WuYiFan0108 can you use the latest dev image to try it again? because i learn that it maybe cause the milvus issue image tag: milvusdb/milvus:2.3-20231227-26b1853c-amd64

Still having the same issue. 
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/712a5ee5-4cbe-4c52-a736-ceb103e902fc)
![image](https://github.com/zilliztech/milvus-cdc/assets/139840531/f2fe15af-05f7-489a-910a-269731d9ddcc)

**Comment by WuYiFan0108** [comment]
@SimFG Seems that milvus dev image milvusdb/milvus:2.3-20231227-eb11b1a5 works fine.

**Comment by SimFG** [comment]
@WuYiFan0108 thanks your feedback. This is a hidden milvus bug and it should have been fixed recently.
If you encounter other issue, please open a new issue.

**Comment by WuYiFan0108** [comment]
@SimFG Hi, is there a link to this hidden milvus bug? Just want to learn something from it.

**Comment by SimFG** [comment]
@WuYiFan0108 the recent similar issue: https://github.com/milvus-io/milvus/issues/29426
