### ISSUE TITLE
[Feature]: cdc when to support etcd ssl config？

### ISSUE THREAD

**Issue by yunurs** [zilliztech/milvus-cdc#51]
### Is your feature request related to a problem? Please describe.

my etcd cluster is open the ssl，so when i use milvus-cdc，i must config the etcd ssl，but i dont konw how to config the etcd ssl，support it yet？

**Comment by SimFG** [comment]
@yunurs Sorry for the late reply, I will develop it in the next version.

**Comment by SimFG** [comment]
@yunurs i have merged the pr to the main branch. and you can try to compile this branch to try to use this feature.
