### ISSUE TITLE
[funcutil/policy.go:43] ["GetExtension fail"] [error="proto: not an extendable proto.Message"] [proxy/privilege_interceptor.go:94] ["GetPrivilegeExtObj err"] [error="proto: not an extendable proto.Message"]

### ISSUE THREAD

**Issue by RebeccaShi-Hub** [zilliztech/milvus-cdc#53]
### Current Behavior

when the cdc server prints the following logs:
[reader/replicate_channel_manager.go:1224] ["receive msg"] [msg=Insert] [data_len=1]
[writer/channel_writer.go:166] ["replicate msg"] [channel=by-test-rootcoord-dml_0] [type=Insert] [collection=user_head_vector] [partition=_default] [insert_data_len=1]
Synchronization data is successfully written to the message queue of the targetMilvus[channel=by-test-rootcoord-dml_0]
But,the log generated by the server of the targetMilvus is the following logs:
[funcutil/policy.go:43] ["GetExtension fail"] [error="proto: not an extendable proto.Message"]
[proxy/privilege_interceptor.go:94] ["GetPrivilegeExtObj err"] [error="proto: not an extendable proto.Message"]
And In fact, the collection corresponding to the targetMilvus does not display any data

**Comment by SimFG** [comment]
@RebeccaShi-Hub you can check the cdc log whether there are some logs which contains `insert_data_len`

**Comment by SimFG** [comment]
@RebeccaShi-Hub the target milvus does not display any data, maybe because the collection isn't loaded.

**Comment by RebeccaShi-Hub** [comment]
Yes, the cdc has a print log insert_data_len=1，and the collection is loaded,but no any data

**Comment by SimFG** [comment]
@RebeccaShi-Hub how do you display the milvus data?

**Comment by SimFG** [comment]
yes, the log can prove the data has been sent to the target milvus. you can try to use the `birdwatcher` to check the collection state, like `show collections` or `show segments`. Or you can search the target milvus log to find some warn or error log, which will be helpful for me to solve your problem.
