### ISSUE TITLE
[Feature]: Can the downstream cluster receive requests when the upstream cluster is experiencing issues?

### ISSUE THREAD

**Issue by anhnch30820** [zilliztech/milvus-cdc#55]
### Is your feature request related to a problem? Please describe.

With the ttMsgEnabled: false in the downstream cluster, it does not allow update, delete, or insert operations. If my upstream cluster experiences an issue, how can the downstream cluster receive requests at that time instead of the upstream cluster?

**Comment by SimFG** [comment]
Make sure that the upstream messages have been fully consumed, and then you can change the configuration in the downstream milvus service: ttMsgEnabled -> true

**Comment by anhnch30820** [comment]
How can I change this configuration? I see two ways - either Reinstall Milvus or modify the user.yaml file in the Configmap. Are there any other ways to do this?

**Comment by SimFG** [comment]
@anhnch30820 How did you deploy milvus? If it is k8s, the config map can be modified.

**Comment by anhnch30820** [comment]
I deployed with helm on K8s, but when I try to modify ttMsgEnabled -> true in config map , I still can't insert with error MilvusException: (code=1303, message=deny to write the message to mq). Do I need to redeploy any components in Milvus?

**Comment by SimFG** [comment]
@anhnch30820 How did you modify this config map? It feels like the modification method is wrong.

**Comment by anhnch30820** [comment]
@SimFG I just edit config map and then change value false -> true. Is this way correct?
Here is full data in config map
data:
  default.yaml: "# Copyright (C) 2019-2021 Zilliz. All rights reserved.\n#\n# Licensed
    under the Apache License, Version 2.0 (the \"License\"); you may not use this
    file except in compliance\n# with the License. You may obtain a copy of the License
    at\n#\n# http://www.apache.org/licenses/LICENSE-2.0\n#\n# Unless required by applicable
    law or agreed to in writing, software distributed under the License\n# is distributed
    on an \"AS IS\" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express\n#
    or implied. See the License for the specific language governing permissions and
    limitations under the License.\n\netcd:\n  endpoints:\n    - milvus-etcd:2379\n\nmetastore:\n
    \ type: etcd\n\nminio:\n  address: milvus-minio\n  port: 9000\n  accessKeyID:
    minioadmin\n  secretAccessKey: minioadmin\n  useSSL: false\n  bucketName: milvus-bucket\n
    \ rootPath: file\n  useIAM: false\n  iamEndpoint: \n  region: \n  useVirtualHost:
    false\n\nmq:\n  type: kafka\n\nmessageQueue: kafka\n\nkafka:\n  brokerList: milvus-kafka:9092\n\nrootCoord:\n
    \ address: milvus-rootcoord\n  port: 53100\n  enableActiveStandby: true  # Enable
    rootcoord active-standby\n\nproxy:\n  port: 19530\n  internalPort: 19529\n\nqueryCoord:\n
    \ address: milvus-querycoord\n  port: 19531\n\n  enableActiveStandby: true  #
    Enable querycoord active-standby\n\nqueryNode:\n  port: 21123\n  enableDisk: true
    # Enable querynode load disk index, and search on disk index\n\nindexCoord:\n
    \ address: milvus-indexcoord\n  port: 31000\n  enableActiveStandby: true  # Enable
    indexcoord active-standby\n\nindexNode:\n  port: 21121\n  enableDisk: true # Enable
    index node build disk vector index\n\ndataCoord:\n  address: milvus-datacoord\n
    \ port: 13333\n  enableActiveStandby: true  # Enable datacoord active-standby\n\ndataNode:\n
    \ port: 21124\n\nlog:\n  level: info\n  file:\n    rootPath: \"\"\n    maxSize:
    300\n    maxAge: 10\n    maxBackups: 20\n  format: text\n"
  user.yaml: |-
    common:
      gracefulTime: 800
      ttMsgEnabled: true

**Comment by SimFG** [comment]
@anhnch30820 It seems that there is no error. You can try to enter the pod and then enter the `configs` directory, where there is a user.yaml file. You can confirm whether the configuration in this file has been changed.

**Comment by anhnch30820** [comment]
@SimFG I try to exec the pod and then enter the configs directory, its value is still false. I tried restarting one pod and exec, its value is true. So how does milvus actually work?

**Comment by SimFG** [comment]
@anhnch30820 yes, if `ttMsgEnabled` config value is true, the milvus will be able to work properly.

Normally, milvus can support dynamic configuration changes. I don't know why the config map doesn't work properly, because I usually change the configuration in this way. There may be an operation problem. You can carefully confirm the steps to modify the config map. And then you will be able to see the updated value after entering the pod after the modification.

**Comment by anhnch30820** [comment]
@SimFG I deployed milvus 2.4.1 by helm with chart --version 4.1.30. Do I have to edit the config value in the values.yaml file to have dynamic configuration changes?

**Comment by SimFG** [comment]
@anhnch30820 You can try it, I don't know much about this part

**Comment by anhnch30820** [comment]
@SimFG I see document in K8s
A container using a ConfigMap as a [subPath](https://kubernetes.io/docs/concepts/storage/volumes#using-subpath) volume mount will not receive ConfigMap updates.
And helm use subPath:
```
- name: milvus-config
  mountPath: /milvus/configs/user.yaml
  subPath: user.yaml
  readOnly: true
```
How can you change it and make it work?

**Comment by SimFG** [comment]
ahhhhh, I don't know much about this part, you can try asking under milvus repo.

**Comment by anhnch30820** [comment]
@SimFG when I deployed milvus-cdc, upstream used kafka and downstream used pulsar. I get log WARN, i don't know what it is and how can i fix them?

[2024/05/30 10:05:45.082 +00:00] [INFO] [writer/channel_writer.go:166] ["replicate msg"] [channel=by-dev-rootcoord-dml_9] 
[type=Insert] [collection=hihi] [partition=_default] [insert_data_len=1]
Thu, May 30 2024 5:05:45 pm[2024/05/30 10:05:45.151 +00:00] [WARN] [retry/retry.go:46] ["retry func failed"] [retried=0] [error="getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error"] [errorVerbose="getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error\n(1) attached stack trace\n -- stack trace:\n | [github.com/milvus-io/milvus-sdk-go/v2/client.handleRespStatus\n](http://github.com/milvus-io/milvus-sdk-go/v2/client.handleRespStatus/n) | \t/go/pkg/mod/[github.com/milvus-io/milvus-sdk-go/v2@v2.3.5/client/collection.go:39\n](http://github.com/milvus-io/milvus-sdk-go/v2@v2.3.5/client/collection.go:39/n) | [github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).ReplicateMessage\n](http://github.com/milvus-io/milvus-sdk-go/v2/client.(*GrpcClient).ReplicateMessage/n) | \t/go/pkg/mod/[github.com/milvus-io/milvus-sdk-go/v2@v2.3.5/client/mq_message.go:34\n](http://github.com/milvus-io/milvus-sdk-go/v2@v2.3.5/client/mq_message.go:34/n) | [github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).ReplicateMessage.func1\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).ReplicateMessage.func1/n) | \t/app/core/writer/milvus_handler.go:280\n | [github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp.func1.1\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp.func1.1/n) | \t/app/core/writer/milvus_handler.go:87\n | [github.com/milvus-io/milvus/pkg/util/retry.Do\n](http://github.com/milvus-io/milvus/pkg/util/retry.Do/n) | \t/go/pkg/mod/[github.com/!sim!f!g/milvus/pkg@v0.0.0-20240126152941-561b213af6d1/util/retry/retry.go:44\n](http://github.com/!sim!f!g/milvus/pkg@v0.0.0-20240126152941-561b213af6d1/util/retry/retry.go:44/n) | [github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp.func1\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp.func1/n) | \t/app/core/writer/milvus_handler.go:86\n | [github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).milvusOp/n) | \t/app/core/writer/milvus_handler.go:100\n | [github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).ReplicateMessage\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*MilvusDataHandler).ReplicateMessage/n) | \t/app/core/writer/milvus_handler.go:279\n | [github.com/zilliztech/milvus-cdc/core/writer.(*replicateMessageHandler).startHandleMessageLoop.func1\n](http://github.com/zilliztech/milvus-cdc/core/writer.(*replicateMessageHandler).startHandleMessageLoop.func1/n) | \t/app/core/writer/replicate_message_manager.go:74\n | runtime.goexit\n | \t/usr/local/go/src/runtime/asm_amd64.s:1571\nWraps: (2) getSegmentID failed: SegmentIDAllocator failRemainRequest unexpected error\nError types: (1) *withstack.withStack (2) *errutil.leafError"]

**Comment by SimFG** [comment]
@anhnch30820 It seems that target milvus has an exception. You can check the status of target milvus.

**Comment by anhnch30820** [comment]
@SimFG  I have another question, in the configs folder I found two files, collection_start_position.yaml and msg_count.yaml, but the documentation does not mention the configs in these two files. So to run the CDC, do I necessarily need these two files or is the cdc.yaml file alone sufficient?

**Comment by SimFG** [comment]
@anhnch30820 Running the cdc service only requires one file, cdc.yaml. The other two files are required by other cdc tools, which are being improved.

**Comment by SimFG** [comment]
@anhnch30820 i will close the issue and if you have other problem, please open a new issue
